name: Unit Tests

on:
  workflow_dispatch:
  push:
   branches:
     - rpena/unit-test-prototype

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Clone h5p-cli repository
        run: git clone https://github.com/h5p/h5p-cli.git

      - name: Install h5p-cli from specific branch, install relevant libraries
        run: |
          ls
          cd h5p-cli
          npm install
          cd ..
          npm install -g ./h5p-cli
          mkdir h5p-environment
          cd h5p-environment
          h5p core
          ls

      # - name: Set Folder Name from Library.json
      #   run: |
      #      echo 'FOLDER_NAME<<EOF' >> $GITHUB_ENV
      #      node compute-version.js >> $GITHUB_ENV
      #      echo 'EOF' >> $GITHUB_ENV
      
      - name: Checkout True False into CLI Environment
        uses: actions/checkout@v3
        with:
          path: h5p-environment/libraries/H5P.TrueFalse-CI

      - name: Install True False Library
        run: |
          cd h5p-environment/libraries/H5P.TrueFalse-CI
          npm install
      
      - name: Install True False Library Dependencies
        run: |
          cd h5p-environment
          h5p deps /libraries/H5P.TrueFalse-CI
          cd /libraries/H5P.TrueFalse-CI
          ls
  
      # - name: Clone E2E Test Repo
      #   run: git clone https://github.com/h5p/h5pcom-e2e-tests.git

      # - name: Install Test Repo
      #   run: |
      #    cd h5pcom-e2e-tests
      #    npm ci

      # - name: Install Playwright Browsers
      #   run: |
      #    cd h5pcom-e2e-tests
      #    npx playwright install-deps

      # - name: Start H5P CLI Server
      #   run: |
      #    cd h5p-environment
      #    h5p server 8080 &

      # - name: Wait for H5P CLI Server
      #   run: curl --retry 10 --retry-connrefused http://localhost:8080

      # - name: Run E2E Tests
      #   run: |
      #    cd h5pcom-e2e-tests
      #    npm run test:libraries